[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#000000'
foreground = '#e5e5e5'

[colors.normal]
black = '#000000'
red = '#cd0000'
green = '#00cd00'
yellow = '#cdcd00'
blue = '#0000ee'
magenta = '#cd00cd'
cyan = '#00cdcd'
white = '#e5e5e5'

[colors.bright]
black = '#7f7f7f'
red = '#ff0000'
green = '#00ff00'
yellow = '#ffff00'
blue = '#5c5cff'
magenta = '#ff00ff'
cyan = '#00ffff'
white = '#ffffff'

[colors.cursor]
cursor = '#cccccc'
text = '#000000'

[colors.selection]
background = '#555555'
text = '#e5e5e5'

[font]
size = 9.4

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4
